// Auto-generated by scripts/generate-changelog-page-data.mjs
export const generatedChangelogData = {
  "generatedAt": "2026-03-31T20:04:14.038Z",
  "surfaces": [
    {
      "id": "web",
      "name": "Web companion",
      "description": "Marketing site, web companion access, linking, recovery, and public product pages.",
      "version": "0.2.2",
      "repoPath": "/Users/christiantonny/Dev/daylens-web",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "505e9e7",
      "recentCommits": [
        {
          "date": "2026-03-31",
          "shortHash": "505e9e7",
          "subject": "Fix font on marketing pages: .lp was hardcoding Apple system font stack, use Inter variable"
        },
        {
          "date": "2026-03-31",
          "shortHash": "ba17f08",
          "subject": "Fix font on Windows: use var(--font-inter) instead of literal \"Inter\" string"
        },
        {
          "date": "2026-03-31",
          "shortHash": "9707c44",
          "subject": "Fix favicons: use app-icon.png with /daylens basePath prefix, fix manifest paths"
        },
        {
          "date": "2026-03-31",
          "shortHash": "9a285d7",
          "subject": "Fix roadmap panels: solid dark bg, accent border — glass blur washed out on white background"
        },
        {
          "date": "2026-03-31",
          "shortHash": "65dbfe1",
          "subject": "Add roadmap/changelog pages, restore mock UI, glassmorphism polish"
        },
        {
          "date": "2026-03-31",
          "shortHash": "0a5704c",
          "subject": "docs: align daylens web onboarding flow"
        },
        {
          "date": "2026-03-31",
          "shortHash": "36ec81b",
          "subject": "Make feature screenshots larger with macOS window chrome"
        },
        {
          "date": "2026-03-31",
          "shortHash": "c7c9a39",
          "subject": "Redirect unauthenticated users to /link instead of /"
        },
        {
          "date": "2026-03-31",
          "shortHash": "ddd3be8",
          "subject": "Add /docs to public paths in middleware"
        },
        {
          "date": "2026-03-31",
          "shortHash": "d0cb88f",
          "subject": "Fix Next.js Image src paths — include /daylens/ basePath prefix"
        }
      ]
    },
    {
      "id": "mac",
      "name": "macOS app",
      "description": "Native SwiftUI app focused on timeline understanding, reports, focus, and Insights.",
      "version": "1.0.23",
      "repoPath": "/Users/christiantonny/Dev/daylens",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "fb6eb95",
      "recentCommits": [
        {
          "date": "2026-03-31",
          "shortHash": "fb6eb95",
          "subject": "Prepare open-source launch"
        },
        {
          "date": "2026-03-31",
          "shortHash": "e994ebb",
          "subject": "Add reports, widgets, AI insights routing, and focus improvements"
        },
        {
          "date": "2026-03-27",
          "shortHash": "f64fcec",
          "subject": "feat: add focus planner and prep v1.0.21 release"
        },
        {
          "date": "2026-03-27",
          "shortHash": "3639d79",
          "subject": "chore: release v1.0.20"
        },
        {
          "date": "2026-03-27",
          "shortHash": "c9265c0",
          "subject": "Add reports, profiles, and work context timeline"
        },
        {
          "date": "2026-03-25",
          "shortHash": "895655a",
          "subject": "fix: preserve fullscreen playback tracking in v1.0.19"
        },
        {
          "date": "2026-03-24",
          "shortHash": "00d5bea",
          "subject": "fix: preserve fullscreen tracking and prep v1.0.18 release"
        },
        {
          "date": "2026-03-23",
          "shortHash": "51ae0d7",
          "subject": "feat: hide apps/sites, fix update relaunch, suppress dev update banner"
        },
        {
          "date": "2026-03-23",
          "shortHash": "2d91893",
          "subject": "fix: always fetch latest release URL before downloading update"
        },
        {
          "date": "2026-03-23",
          "shortHash": "e49a3f2",
          "subject": "fix: strip quarantine xattr after update install and clean up backups"
        }
      ]
    },
    {
      "id": "windows",
      "name": "Windows app",
      "description": "Electron app focused on parity, updater flow, Windows packaging, and UI polish.",
      "version": "1.0.14",
      "repoPath": "/Users/christiantonny/Dev/daylens-windows",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "f84d1af",
      "recentCommits": [
        {
          "date": "2026-03-31",
          "shortHash": "f84d1af",
          "subject": "release richer in-app update notes"
        },
        {
          "date": "2026-03-31",
          "shortHash": "18a07bb",
          "subject": "fix in-app update install flow"
        },
        {
          "date": "2026-03-31",
          "shortHash": "eebc03f",
          "subject": "fix startup and refresh release flow"
        },
        {
          "date": "2026-03-31",
          "shortHash": "ec54b71",
          "subject": "fix: guard migration v5 against fresh installs that already have visit_time_us"
        },
        {
          "date": "2026-03-31",
          "shortHash": "77b1357",
          "subject": "fix: prevent 'No data' yesterday badge from wrapping to two lines"
        },
        {
          "date": "2026-03-31",
          "shortHash": "46e90b9",
          "subject": "fix: improve responsive layout for Focus and Today views"
        },
        {
          "date": "2026-03-26",
          "shortHash": "d958b06",
          "subject": "docs: add windows parity contracts"
        },
        {
          "date": "2026-03-25",
          "shortHash": "4b1e5dc",
          "subject": "feat: bundle app font and polish update banner"
        },
        {
          "date": "2026-03-25",
          "shortHash": "be42b3b",
          "subject": "Fix Windows release workflow secret gating"
        },
        {
          "date": "2026-03-25",
          "shortHash": "9e64bba",
          "subject": "Refine release layout and cut 1.0.10"
        }
      ]
    }
  ]
} as const;
