// Auto-generated by scripts/generate-changelog-page-data.mjs
export const generatedChangelogData = {
  "generatedAt": "2026-03-31T22:19:41.414Z",
  "surfaces": [
    {
      "id": "web",
      "name": "Web companion",
      "description": "Marketing site, web companion access, linking, recovery, and public product pages.",
      "version": "0.2.2",
      "repoPath": "/Users/christiantonny/Dev/daylens-web",
      "latestCommitDateTime": "2026-03-31T23:54:09+02:00",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "ccda537",
      "recentCommits": [
        {
          "dateTime": "2026-03-31T23:54:09+02:00",
          "date": "2026-03-31",
          "shortHash": "ccda537",
          "subject": "Rebuild roadmap and changelog in Raycast style"
        },
        {
          "dateTime": "2026-03-31T23:32:44+02:00",
          "date": "2026-03-31",
          "shortHash": "8a5c030",
          "subject": "Auto-organize changelog entries"
        },
        {
          "dateTime": "2026-03-31T23:28:14+02:00",
          "date": "2026-03-31",
          "shortHash": "d63da96",
          "subject": "Redesign roadmap as hub-style directory"
        },
        {
          "dateTime": "2026-03-31T23:24:31+02:00",
          "date": "2026-03-31",
          "shortHash": "23bb3f5",
          "subject": "Fix changelog ordering and title formatting"
        },
        {
          "dateTime": "2026-03-31T23:17:20+02:00",
          "date": "2026-03-31",
          "shortHash": "1b755d0",
          "subject": "Trim changelog archive clutter"
        },
        {
          "dateTime": "2026-03-31T22:58:52+02:00",
          "date": "2026-03-31",
          "shortHash": "0cfcddd",
          "subject": "Rebuild changelog in Dia-style archive layout"
        },
        {
          "dateTime": "2026-03-31T22:52:19+02:00",
          "date": "2026-03-31",
          "shortHash": "d9e7707",
          "subject": "Feature major Windows changelog update"
        },
        {
          "dateTime": "2026-03-31T22:46:41+02:00",
          "date": "2026-03-31",
          "shortHash": "95b07c6",
          "subject": "Refresh changelog after Windows AI update"
        },
        {
          "dateTime": "2026-03-31T22:08:14+02:00",
          "date": "2026-03-31",
          "shortHash": "baeafae",
          "subject": "Sync changelog and refine product pages"
        },
        {
          "dateTime": "2026-03-31T18:13:48+02:00",
          "date": "2026-03-31",
          "shortHash": "505e9e7",
          "subject": "Fix font on marketing pages: .lp was hardcoding Apple system font stack, use Inter variable"
        }
      ]
    },
    {
      "id": "mac",
      "name": "macOS app",
      "description": "Native SwiftUI app focused on timeline understanding, reports, focus, and Insights.",
      "version": "1.0.24",
      "repoPath": "/Users/christiantonny/Dev/daylens",
      "latestCommitDateTime": "2026-03-31T18:37:26+02:00",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "fb6eb95",
      "recentCommits": [
        {
          "dateTime": "2026-03-31T18:37:26+02:00",
          "date": "2026-03-31",
          "shortHash": "fb6eb95",
          "subject": "Prepare open-source launch"
        },
        {
          "dateTime": "2026-03-31T18:37:19+02:00",
          "date": "2026-03-31",
          "shortHash": "e994ebb",
          "subject": "Add reports, widgets, AI insights routing, and focus improvements"
        },
        {
          "dateTime": "2026-03-27T15:27:37+02:00",
          "date": "2026-03-27",
          "shortHash": "f64fcec",
          "subject": "feat: add focus planner and prep v1.0.21 release"
        },
        {
          "dateTime": "2026-03-27T10:27:00+02:00",
          "date": "2026-03-27",
          "shortHash": "3639d79",
          "subject": "chore: release v1.0.20"
        },
        {
          "dateTime": "2026-03-27T09:49:14+02:00",
          "date": "2026-03-27",
          "shortHash": "c9265c0",
          "subject": "Add reports, profiles, and work context timeline"
        },
        {
          "dateTime": "2026-03-25T18:24:32+02:00",
          "date": "2026-03-25",
          "shortHash": "895655a",
          "subject": "fix: preserve fullscreen playback tracking in v1.0.19"
        },
        {
          "dateTime": "2026-03-24T20:31:27+02:00",
          "date": "2026-03-24",
          "shortHash": "00d5bea",
          "subject": "fix: preserve fullscreen tracking and prep v1.0.18 release"
        },
        {
          "dateTime": "2026-03-23T08:13:57+02:00",
          "date": "2026-03-23",
          "shortHash": "51ae0d7",
          "subject": "feat: hide apps/sites, fix update relaunch, suppress dev update banner"
        },
        {
          "dateTime": "2026-03-23T07:38:47+02:00",
          "date": "2026-03-23",
          "shortHash": "2d91893",
          "subject": "fix: always fetch latest release URL before downloading update"
        },
        {
          "dateTime": "2026-03-23T07:28:56+02:00",
          "date": "2026-03-23",
          "shortHash": "e49a3f2",
          "subject": "fix: strip quarantine xattr after update install and clean up backups"
        }
      ]
    },
    {
      "id": "windows",
      "name": "Windows app",
      "description": "Electron app focused on parity, updater flow, Windows packaging, and UI polish.",
      "version": "1.0.15",
      "repoPath": "/Users/christiantonny/Dev/daylens-windows",
      "latestCommitDateTime": "2026-03-31T22:37:03+02:00",
      "latestCommitDate": "2026-03-31",
      "latestCommitHash": "e3c64de",
      "recentCommits": [
        {
          "dateTime": "2026-03-31T22:37:03+02:00",
          "date": "2026-03-31",
          "shortHash": "e3c64de",
          "subject": "Add multi-provider AI support for Windows"
        },
        {
          "dateTime": "2026-03-31T18:20:15+02:00",
          "date": "2026-03-31",
          "shortHash": "f84d1af",
          "subject": "release richer in-app update notes"
        },
        {
          "dateTime": "2026-03-31T18:10:25+02:00",
          "date": "2026-03-31",
          "shortHash": "18a07bb",
          "subject": "fix in-app update install flow"
        },
        {
          "dateTime": "2026-03-31T17:26:37+02:00",
          "date": "2026-03-31",
          "shortHash": "eebc03f",
          "subject": "fix startup and refresh release flow"
        },
        {
          "dateTime": "2026-03-31T17:08:54+02:00",
          "date": "2026-03-31",
          "shortHash": "ec54b71",
          "subject": "fix: guard migration v5 against fresh installs that already have visit_time_us"
        },
        {
          "dateTime": "2026-03-31T17:05:10+02:00",
          "date": "2026-03-31",
          "shortHash": "77b1357",
          "subject": "fix: prevent 'No data' yesterday badge from wrapping to two lines"
        },
        {
          "dateTime": "2026-03-31T15:30:55+02:00",
          "date": "2026-03-31",
          "shortHash": "46e90b9",
          "subject": "fix: improve responsive layout for Focus and Today views"
        },
        {
          "dateTime": "2026-03-26T23:15:39+02:00",
          "date": "2026-03-26",
          "shortHash": "d958b06",
          "subject": "docs: add windows parity contracts"
        },
        {
          "dateTime": "2026-03-25T00:43:23+02:00",
          "date": "2026-03-25",
          "shortHash": "4b1e5dc",
          "subject": "feat: bundle app font and polish update banner"
        },
        {
          "dateTime": "2026-03-25T00:13:04+02:00",
          "date": "2026-03-25",
          "shortHash": "be42b3b",
          "subject": "Fix Windows release workflow secret gating"
        }
      ]
    }
  ]
} as const;
